### ISSUE TITLE
LAB 18

### ISSUE THREAD

**Issue by UsingCoding** [DenPetrov11032001/basic-of-programming#2]
### 18.1

- [x] Программа не заврешает запрос данных от пользователя после ввода 4-ех строк значений. Если у вас не так, прошу отписать сюда в комменты
![3](https://user-images.githubusercontent.com/46163357/78279192-d703ae00-751f-11ea-9a5f-60ddeb4c527e.png)

### 18.2

- [x] Магия... лучше вынести в константы
https://github.com/DenPetrov11032001/basic-of-programming/blob/cb8411eb64ccde81989cee9a2b56934ac97c04b8/lw18/18_2.pas#L50

- [x] Переменная "имя файла".., которая и есть файл. Из названия не понятно для чего она нужна
https://github.com/DenPetrov11032001/basic-of-programming/blob/cb8411eb64ccde81989cee9a2b56934ac97c04b8/lw18/18_2.pas#L13

**Comment by denis-petrov** [comment]
Не так

**Comment by UsingCoding** [comment]
### Про не рабочую программу и постоянный запрос у пользователя
Здесь у вас проверяется переменная WhichScore, перечислимого типа данных {1...4} , следовательно она никогда не будет равна 5, просто не может компилятор этого допустить, вот и цикл не останавливается. Раз у вас работает, то скорее всего dev gpc пропускает проверку или позволяет увеличить до 5-ки, или сам как-то это обрабатывает. В общем всё равно поведение может быть не определено, стоит исправить
https://github.com/DenPetrov11032001/basic-of-programming/blob/cb8411eb64ccde81989cee9a2b56934ac97c04b8/lw18/18_1.pas#L22

**Comment by UsingCoding** [comment]
- [x] То же самое https://github.com/DenPetrov11032001/basic-of-programming/issues/2#issuecomment-608006640 наблюдается и в 18.2

**Comment by UsingCoding** [comment]
- [x] По-прежнему наблюдается та же болячка https://github.com/DenPetrov11032001/basic-of-programming/issues/2#issuecomment-608006640. Если есть вопросы можете мне написать - обсудим

- [x] Ещё немного магии
https://github.com/DenPetrov11032001/basic-of-programming/blob/413f1ca983e8ea539d480e314678438c31bd23d5/lw18/18_1.pas#L23

**Comment by UsingCoding** [comment]
### 18.2

- [x] Работает всё норм, только теперь можно ввести как значение 200, а максимальное значение 100, но при этом программа продолжает работать и даже считает

**Comment by UsingCoding** [comment]
### 18.2

- [x] Наблюдается всё та же проблема https://github.com/DenPetrov11032001/basic-of-programming/issues/2#issuecomment-609934468. Симптомы проблемы те же, что были у проблемы с непрерывным считыванием. Намёк моего компилятора(он ругается на 54 строку, просто мне пришлось одну строчку в начале программы добавить, чтобы у меня работало чтение/запись из файла `ASSIGN(NameStudentFile, '1.txt')` )
![screen](https://user-images.githubusercontent.com/46163357/78813855-55f05f00-79d6-11ea-99b6-27f18f771e68.png)
